name: 'Setup Java JDK'
description: 'Set up versions of the Java JDK and add the command-line tools to the PATH'

inputs:
  java-version:
   description: 'The Java version to set up. Takes main, next, or a whole or semver Java version.'
   required: false
   default: 'main'

runs:
  using: composite
  steps:
    - uses: mp911de/some-actions/env-config@main
      id: ci-properties
      name: Load CI properties
    - uses: actions/setup-java@v5
      if: ${{ contains(fromJson(steps.ci-properties.outputs.ci-properties).java, inputs.java-version) }}
      with:
        java-version: '${{ fromJson(steps.ci-properties.outputs.ci-properties).java[inputs.java-version] }}'
        distribution: '${{ fromJson(steps.ci-properties.outputs.ci-properties).java.dist }}'
    - uses: actions/setup-java@v5
      if: ${{ inputs.java-version != 'main' && inputs.java-version != 'next' }}
      with:
        java-version: '${{ inputs.java-version}}'
        distribution: '${{ env.JAVA_DIST }}'

